blog/urls.py
from django.urls import path
from blog import views

urlpatterns = [
    path('bloglist',views.BlogListView.as_view(),name='blog-bloglist'),
    path('bloggrid',views.BlogGridView.as_view(),name='blog-bloggrid'),
    path('blogdetails',views.BlogDetailsView.as_view(),name='blog-blogdetails'),
]

projects/urls.py
from django.urls import path
from projects import views
app_name = 'projects'

urlpatterns = [
    path('projectsgrid',views.ProjectsGridView.as_view(),name='projects-projectsgrid'),
    path('projectslist',views.ProjectsListView.as_view(),name='projects-projectslist'),
    path('projectoverview',views.ProjectOverviewView.as_view(),name='projects-projectoverview'),
    path('createview',views.CreateViewView.as_view(),name='projects-createview'),
    

    path('report',views.ProjectsListView.as_view(),name='report'),
    path('gift',views.ProjectsListView.as_view(),name='gift'),
    path('batches',views.ProjectsListView.as_view(),name='batches'),
    path('customers',views.ProjectsListView.as_view(),name='customers'),
    path('recurring',views.ProjectsListView.as_view(),name='recurring'),
    path('send_payment',views.ProjectsListView.as_view(),name='send_payment'),
    path('settings',views.ProjectsListView.as_view(),name='settings'),
    path('help',views.ProjectsListView.as_view(),name='help'),
]

skote/urls.py
from django.urls import reverse
from django.contrib import admin
from django.urls import path,include
from skote import views
from .views import MyPasswordSetView ,MyPasswordChangeView
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from account2.views import login_view
from pages.views import home

urlpatterns = [
    path('admin/', admin.site.urls),

    # Dashboards View

    path('',home.as_view(),name='home'),
    path('/account/dashboard2', login_required(views.DashboardView.as_view(), login_url='account_login'), name='dashboard'),

    path('account/login/', login_view, name='account_login'),

    #path('',views.DashboardView.as_view(),name='dashboard'),
    path('dashboard_saas',views.SaasView.as_view(),name='dashboard_saas'),
    path('dashboard_crypto',views.CryptoView.as_view(),name='dashboard_crypto'),
    path('dashboard_blog',views.BlogView.as_view(),name='dashboard_blog'),
    path('dashboard_jobs',views.JobsView.as_view(),name='dashboard_jobs'),
    # Calender View
    path('calendar',views.CalendarView.as_view(),name='calendar'),
    path('full-calendar',views.CalendarFullView.as_view(),name='full-calendar'),
    # Chat View
    path('chat',views.ChatView.as_view(),name='chat'),
    # Layouts
    path('layout/',include('layout.urls')),
    # File manager View
    path('filemanager',views.FileManagerView.as_view(),name='filemanager'),
    #Ecommerce
    path('ecommerce/',include("ecommerce.urls")),
    #Crypto
    path('crypto/',include('crypto.urls')),
    #Email
    path("email/",include("e_mail.urls")),
    #Invoices
    path('invoices/',include('invoices.urls')),
    #Projects
    path('projects/',include('projects.urls')),
    #Tasks
    path('tasks/',include('tasks.urls')),
    #Blog
    path('blog/',include('blog.urls')),
    #Blog
    path('jobs/',include('jobs.urls')),
    #Blog
    path('contacts/',include('contacts.urls')),
    #Authencation
    # path('authentication/',include('authentication.urls')),
    #Pages
    path('pages/',include('pages.urls')),
    #Components
    path('components/',include('components.urls')),
    # Allauth
    #path('account/', include('allauth.urls')),
    path('account/', include('account2.urls')),
    #path('account/login/', views.AccountLoginView.as_view(), name='account_login'),
   

    path('transactions/', include('transactions.urls')),
     path('customers/', include('customers.urls')),
    

    path('auth-logout/',TemplateView.as_view(template_name="account/logout-success.html"),name ='pages-logout'),
    path('auth-lockscreen/',TemplateView.as_view(template_name="account/lock-screen.html"),name ='pages-lockscreen'),
        #Custum change password done page redirect
    path('accounts/password/change/', login_required(MyPasswordChangeView.as_view()), name="account_change_password"),
    #Custum set password done page redirect
    path('accounts/password/set/', login_required(MyPasswordSetView.as_view()), name="account_set_password"),


    

]

projects/models.py
from django.db import models

# Create your models here.

projects/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class ProjectsGridView(LoginRequiredMixin,View):
    def get(self , request):
        greeting = {}
        greeting['heading'] = "Projects Grid"
        greeting['pageview'] = "Projects"
        return render (request,'projects/projectsgrid.html',greeting)

class ProjectsListView(LoginRequiredMixin,View):
    def get(self , request):
        greeting = {}
        greeting['heading'] = "Projects List"
        greeting['pageview'] = "Projects"
        return render (request,'projects/projectslist.html',greeting)

class ProjectOverviewView(LoginRequiredMixin,View):
    def get(self , request):
        greeting = {}
        greeting['heading'] = "Project Overview"
        greeting['pageview'] = "Projects"
        return render (request,'projects/projectsoverview.html',greeting)

class CreateViewView(LoginRequiredMixin,View):
    def get(self , request):
        greeting = {}
        greeting['heading'] = "Create New Project"
        greeting['pageview'] = "Projects"
        return render (request,'projects/createnew.html',greeting)

templates/projects/createnew.html
{% extends 'partials/base.html' %}
{% load static %}


{% block extra_css %}
    <link href="{% static 'libs/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}" rel="stylesheet">

    <!-- dropzone css -->
    <link href="{% static 'libs/dropzone/dist/min/dropzone.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block contents %}


<form id="createproject-form" autocomplete="off" class="needs-validation" novalidate>
                            
    <div class="row">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">  
                    <input type="hidden" class="form-control" id="formAction" name="formAction" value="add">
                    <input type="hidden" class="form-control" id="project-id-input">
                    <div class="mb-3">
                        <label for="projectname-input" class="form-label">Project Name</label>
                        
                        <input id="projectname-input" name="projectname-input" type="text" class="form-control" placeholder="Enter project name..." required>
                        <div class="invalid-feedback">Please enter a project name.</div>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Project Image</label>
                        
                        <div class="text-center">
                            <div class="position-relative d-inline-block">
                                <div class="position-absolute bottom-0 end-0">
                                    <label for="project-image-input" class="mb-0" data-bs-toggle="tooltip" data-bs-placement="right" title="Select Image">
                                        <div class="avatar-xs">
                                            <div class="avatar-title bg-light border rounded-circle text-muted cursor-pointer shadow font-size-16">
                                                <i class='bx bxs-image-alt'></i>
                                            </div>
                                        </div>
                                    </label>
                                    <input class="form-control d-none" value="" id="project-image-input" type="file" accept="image/png, image/gif, image/jpeg">
                                </div>
                                <div class="avatar-lg">
                                    <div class="avatar-title bg-light rounded-circle">
                                        <img src="" id="projectlogo-img" class="avatar-md h-auto rounded-circle" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="projectdesc-input" class="form-label">Project Description</label>
                        <textarea class="form-control" id="projectdesc-input" rows="3" placeholder="Enter project description..." required></textarea>
                        <div class="invalid-feedback">Please enter a project description.</div>
                    </div>
                    <div class="mb-3 position-relative">
                        <label for="task-assign-input" class="form-label">Assigned To</label>

                        <div class="avatar-group justify-content-center" id="assignee-member"></div>

                        <div class="select-element" id="select-element">
                            <button class="btn btn-light w-100 d-flex justify-content-between" type="button" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
                                <span>Assigned To<b id="total-assignee" class="mx-1">0</b>Members</span> <i class="mdi mdi-chevron-down"></i>
                            </button>
                            <div class="dropdown-menu w-100">
                                <div data-simplebar style="max-height: 172px">
                                    <ul class="list-unstyled mb-0 assignto-list">
                                        <li>
                                            <a class="dropdown-item d-flex align-items-center" href="#">
                                                <div class="avatar-xs flex-shrink-0 me-2">
                                                    <img src="/static/images/users/avatar-2.jpg" alt="" class="img-fluid rounded-circle" />
                                                </div>
                                                <div class="flex-grow-1">Tommie Metzler</div>
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item d-flex align-items-center" href="#">
                                                <div class="avatar-xs flex-shrink-0 me-2">
                                                    <img src="/static/images/users/avatar-3.jpg" alt="" class="img-fluid rounded-circle" />
                                                </div>
                                                <div class="flex-grow-1">Paul Barone</div>
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item d-flex align-items-center" href="#">
                                                <div class="avatar-xs flex-shrink-0 me-2">
                                                    <img src="/static/images/users/avatar-4.jpg" alt="" class="img-fluid rounded-circle" />
                                                </div>
                                                <div class="flex-grow-1">Chris Lucas</div>
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item d-flex align-items-center" href="#">
                                                <div class="avatar-xs flex-shrink-0 me-2">
                                                    <img src="/static/images/users/avatar-1.jpg" alt="" class="img-fluid rounded-circle" />
                                                </div>
                                                <div class="flex-grow-1">Shirley North</div>
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item d-flex align-items-center" href="#">
                                                <div class="avatar-xs flex-shrink-0 me-2">
                                                    <img src="/static/images/users/avatar-5.jpg" alt="" class="img-fluid rounded-circle" />
                                                </div>
                                                <div class="flex-grow-1">Patricia Pierce</div>
                                            </a>
                                        </li>

                                        <li>
                                            <a class="dropdown-item d-flex align-items-center" href="#">
                                                <div class="avatar-xs flex-shrink-0 me-2">
                                                    <img src="/static/images/users/avatar-6.jpg" alt="" class="img-fluid rounded-circle" />
                                                </div>
                                                <div class="flex-grow-1">William Max</div>
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item d-flex align-items-center" href="#">
                                                <div class="avatar-xs flex-shrink-0 me-2">
                                                    <img src="/static/images/users/avatar-7.jpg" alt="" class="img-fluid rounded-circle" />
                                                </div>
                                                <div class="flex-grow-1">Johnnie Walton</div>
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item d-flex align-items-center" href="#">
                                                <div class="avatar-xs flex-shrink-0 me-2">
                                                    <img src="/static/images/users/avatar-8.jpg" alt="" class="img-fluid rounded-circle" />
                                                </div>
                                                <div class="flex-grow-1">Miriam Crum</div>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div>
                        <label class="form-label">Attached Files</label>
                        <div class="fallback dropzone" id="myId" enctype="multipart/form-data">
                            <div class="fallback">
                                <input name="file" type="file" multiple />
                            </div>

                            <div class="dz-message needsclick">
                                <div class="mb-3">
                                    <i class="display-4 text-muted bx bxs-cloud-upload"></i>
                                </div>

                                <h4>Drop files here or click to upload.</h4>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end card body -->
            </div>
            <!-- end card -->
            
        </div>
        <!-- end col -->
        <div class="col-lg-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title mb-3">Publish</h5>

                    <div class="mb-3">
                        <label class="form-label" for="project-status-input">Status</label>
                        <select class="form-select" id="project-status-input">
                            <option value="Completed">Completed</option>
                            <option value="Inprogress" selected>Inprogress</option>
                            <option value="Delay">Delay</option>
                        </select>
                        <div class="invalid-feedback">Please select project status.</div>
                    </div>

                    <div>
                        <label class="form-label" for="project-visibility-input">Visibility</label>
                        <select class="form-select" id="project-visibility-input">
                            <option value="Private">Private</option>
                            <option value="Public">Public</option>
                            <option value="Team">Team</option>
                        </select>
                    </div>
                </div>
                <!-- end card body -->
            </div>
            <!-- end card -->

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title mb-3">Due Date</h5>
                    
                    <input type="text" id="duedate-input" class="form-control" placeholder="Select due date" name="due date" data-date-format="dd M, yyyy" data-provide="datepicker" data-date-autoclose="true" required />
                    <div class="invalid-feedback">Please select due date.</div>
                </div>
                <!-- end card body -->
            </div>
            <!-- end card -->
        </div>
        <!-- end col -->

        <div class="col-lg-8">
            <div class="text-end mb-4">
                <button type="submit" class="btn btn-primary">Create Project</button>
            </div>
        </div>
    </div>
    <!-- end row -->
</form>

{% endblock %}

{% block extra_javascript %}

    <!-- bootstrap datepicker -->
    <script src="{% static 'libs/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>

    <!-- dropzone plugin -->
    <script src="{% static 'libs/dropzone/dist/min/dropzone.min.js' %}"></script>

    <script src="{% static 'js/pages/project-create.init.js' %}"></script>

{% endblock %}

templates/projects/projectslist.html
{% extends 'partials/base.html' %}
{% load static %}
{% block extra_css %}


    <!-- DataTables -->
    <link href="{% static 'libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- Responsive datatable examples -->
    <link href="{% static 'libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />  

{% endblock %}

{% block contents %}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-sm">
                        <div class="search-box me-2 d-inline-block">
                            <div class="position-relative">
                                <input type="text" class="form-control" autocomplete="off" id="searchTableList" placeholder="Search...">
                                <i class="bx bx-search-alt search-icon"></i>
                            </div>
                        </div>
                    </div>
                    <!-- end col -->
                    <div class="col-sm-auto">
                        <div class="text-sm-end">
                            <a href="{% url 'projects:projects-createview' %}" class="btn btn-success btn-rounded" id="addProject-btn"><i class="mdi mdi-plus me-1"></i> Add New Project</a>
                        </div>
                    </div>
                    <!-- end col -->
                </div>
                <!-- end row -->
                <div class="">
                    <div class="table-responsive">
                        <table class="table project-list-table align-middle table-nowrap dt-responsive nowrap w-100 table-borderless" id="projectList-table">
                            <thead class="table-light">
                                <tr>
                                    <th scope="col" style="width: 60px">#</th>
                                    <th scope="col">Projects</th>
                                    <th scope="col">Due Date</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Team</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- end card -->
    </div>
</div>
<!-- end row -->
{% endblock %}

{% block extra_content %}          
<!-- Modal -->
<div class="modal fade" id="removeItemModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm">
        <div class="modal-content">
            <div class="modal-body px-4 py-5 text-center">
                <button type="button" class="btn-close position-absolute end-0 top-0 m-3" data-bs-dismiss="modal" aria-label="Close"></button>
                <div class="avatar-sm mb-4 mx-auto">
                    <div class="avatar-title bg-primary text-primary bg-opacity-10 font-size-20 rounded-3">
                        <i class="mdi mdi-trash-can-outline"></i>
                    </div>
                </div>
                <p class="text-muted font-size-16 mb-4">Are you Sure You want to Remove this Order ?</p>
                
                <div class="hstack gap-2 justify-content-center mb-0">
                    <button type="button" class="btn btn-danger" id="remove-item">Remove Now</button>
                    <button type="button" class="btn btn-secondary" id="close-removeProjectModal" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end removeItemModal -->  
 {% endblock %}




{% block extra_javascript %}


    <!-- Required datatable js -->
    <script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js'%}"></script>
    <script src="{% static 'libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js'%}"></script>
    
    <!-- Responsive examples -->
    <script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js'%}"></script>
    <script src="{% static 'libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js'%}"></script>

    <script src="{% static 'js/pages/project-list.init.js'%}"></script>

{% endblock %}