blog/urls.py
from django.urls import path
from blog import views

urlpatterns = [
    path('bloglist',views.BlogListView.as_view(),name='blog-bloglist'),
    path('bloggrid',views.BlogGridView.as_view(),name='blog-bloggrid'),
    path('blogdetails',views.BlogDetailsView.as_view(),name='blog-blogdetails'),
]

customers/urls.py
from django.urls import path,re_path
from . import views

app_name = 'customers'

urlpatterns = [
    re_path('customers_list/', views.customer_list, name='customer_list'),
    path('create/', views.customer_create, name='customer_create'),
    path('add_api_record/', views.customer_detail, name='add_api_record'),
    path('<int:pk>/update/', views.customer_update, name='customer_update'),
    path('<int:pk>/delete/', views.customer_delete, name='customer_delete'),
]

skote/urls.py
from django.urls import reverse
from django.contrib import admin
from django.urls import path,include
from skote import views
from .views import MyPasswordSetView ,MyPasswordChangeView
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from account2.views import login_view
from pages.views import home

urlpatterns = [
    path('admin/', admin.site.urls),

    # Dashboards View

    path('',home.as_view(),name='home'),
    path('/account/dashboard2', login_required(views.DashboardView.as_view(), login_url='account_login'), name='dashboard'),

    path('account/login/', login_view, name='account_login'),

    #path('',views.DashboardView.as_view(),name='dashboard'),
    path('dashboard_saas',views.SaasView.as_view(),name='dashboard_saas'),
    path('dashboard_crypto',views.CryptoView.as_view(),name='dashboard_crypto'),
    path('dashboard_blog',views.BlogView.as_view(),name='dashboard_blog'),
    path('dashboard_jobs',views.JobsView.as_view(),name='dashboard_jobs'),
    # Calender View
    path('calendar',views.CalendarView.as_view(),name='calendar'),
    path('full-calendar',views.CalendarFullView.as_view(),name='full-calendar'),
    # Chat View
    path('chat',views.ChatView.as_view(),name='chat'),
    # Layouts
    path('layout/',include('layout.urls')),
    # File manager View
    path('filemanager',views.FileManagerView.as_view(),name='filemanager'),
    #Ecommerce
    path('ecommerce/',include("ecommerce.urls")),
    #Crypto
    path('crypto/',include('crypto.urls')),
    #Email
    path("email/",include("e_mail.urls")),
    #Invoices
    path('invoices/',include('invoices.urls')),
    #Projects
    path('projects/',include('projects.urls')),
    #Tasks
    path('tasks/',include('tasks.urls')),
    #Blog
    path('blog/',include('blog.urls')),
    #Blog
    path('jobs/',include('jobs.urls')),
    #Blog
    path('contacts/',include('contacts.urls')),
    #Authencation
    # path('authentication/',include('authentication.urls')),
    #Pages
    path('pages/',include('pages.urls')),
    #Components
    path('components/',include('components.urls')),
    # Allauth
    #path('account/', include('allauth.urls')),
    path('account/', include('account2.urls')),
    #path('account/login/', views.AccountLoginView.as_view(), name='account_login'),
   

    path('transactions/', include('transactions.urls')),
     path('customers/', include('customers.urls')),
    

    path('auth-logout/',TemplateView.as_view(template_name="account/logout-success.html"),name ='pages-logout'),
    path('auth-lockscreen/',TemplateView.as_view(template_name="account/lock-screen.html"),name ='pages-lockscreen'),
        #Custum change password done page redirect
    path('accounts/password/change/', login_required(MyPasswordChangeView.as_view()), name="account_change_password"),
    #Custum set password done page redirect
    path('accounts/password/set/', login_required(MyPasswordSetView.as_view()), name="account_set_password"),


    

]

customers/models.py
from django.db import models

class Customer(models.Model):
    customer_id = models.CharField(max_length=20)
    bill_company = models.CharField(max_length=100)
    bill_first_name = models.CharField(max_length=50)
    bill_last_name = models.CharField(max_length=50)
    recurring_schedule = models.CharField(max_length=50)
    bill_phone_number = models.CharField(max_length=20)
    email = models.EmailField()

customers/forms.py
from django import forms
from .models import Customer
class CustomerForm(forms.ModelForm):
    def clean_email(self):
        email = self.cleaned_data.get('email')
        # Custom validation logic for the email field
        # ...
        return email

    class Meta:
        model = Customer
        fields = ['customer_id', 'bill_company', 'bill_first_name', 'bill_last_name', 'recurring_schedule', 'bill_phone_number', 'email']
        # Additional form field customization
        widgets = {
            'recurring_schedule': forms.Select(attrs={'class': 'custom-select'} , choices=[('change1', 'Change 1'), ('change2', 'Change 2')]),
            'bill_phone_number': forms.TextInput(attrs={'placeholder': 'Enter phone number'}),
        }

customers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Customer
from .forms import CustomerForm
from django.urls import reverse

from .filters import CustomerFilter

from rest_framework.decorators import api_view
from rest_framework.response import Response


def customer_list(request):
    customers = Customer.objects.all()
    
    customer_filter = CustomerFilter(request.GET, queryset=Customer.objects.all())

    return render(request, 'customers/customers_list.html', {'customers': customers,'filter': customer_filter})

def customer_create(request):
    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save()
            
            return redirect(reverse('customers:customer_list'))
    else:
        form = CustomerForm()
    button_text = "Add Transaction"
    return render(request, 'customers/customer_create.html', {'form': form, 'button_text': button_text})

def customer_detail(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    return render(request, 'customer_detail.html', {'customer': customer})

def customer_update(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    if request.method == 'POST':
        form = CustomerForm(request.POST or None, instance=customer)
        if form.is_valid():
            form.save()
            return redirect(reverse('customers:customer_list'))
    else:
        form = CustomerForm(instance=customer)
    button_text = "Update Customer"
    return render(request, 'customers/customer_create.html', {'form': form, 'button_text': button_text})
   

def customer_delete(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    if request.method == 'POST':
        customer.delete()
        return redirect(reverse('customers:customer_list'))
    return render(request, 'customers/customer_confirm_delete.html', {'customer': customer})

templates/customers/customer_confirm_delete.html
<p>Are you sure you want to delete transaction "{{ customer.customer_id }}"?</p>

<form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete it</button>
</form>

<a href="{% url 'customers:customer_list' %}">No, cancel</a>

templates/customers/customer_create.html
{% extends 'partials/base.html' %}
{% load static %}

{% load widget_tweaks %}


{% block extra_css %}
    {{ form.media.css }}
{% endblock %}

{% block contents %}

    <h1>Create Customer</h1>

    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.customer_id.id_for_label }}">Customer ID</label>
            {{ form.customer_id|add_class:'form-control' }}
        </div>
        <div class="form-group">
            <label for="{{ form.bill_company.id_for_label }}">Bill Company</label>
            {{ form.bill_company|add_class:'form-control' }}
        </div>
        <div class="form-group">
            <label for="{{ form.bill_first_name.id_for_label }}">Bill First Name</label>
            {{ form.bill_first_name|add_class:'form-control' }}
        </div>
        <div class="form-group">
            <label for="{{ form.bill_last_name.id_for_label }}">Bill Last Name</label>
            {{ form.bill_last_name|add_class:'form-control' }}
        </div>
        <div class="form-group">
            <label for="{{ form.recurring_schedule.id_for_label }}">Recurring Schedule</label>
            {{ form.recurring_schedule|add_class:'form-control' }}
        </div>
        <div class="form-group">
            <label for="{{ form.bill_phone_number.id_for_label }}">Bill Phone Number</label>
            {{ form.bill_phone_number|add_class:'form-control' }}
        </div>
        <div class="form-group">
            <label for="{{ form.email.id_for_label }}">Email</label>
            {{ form.email|add_class:'form-control' }}
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>

{% endblock %}

{% block extra_javascript %}
    {{ form.media.js }}
{% endblock %}

templates/customers/customers_list.html
{% extends 'partials/base.html' %}
{% load static %}
{% block extra_css %}

    <!-- DataTables -->
    <link href="{% static 'libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- Responsive datatable examples -->
    <link href="{% static 'libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />  

{% endblock %}

{% block contents %}

<script type="text/javascript">
function confirmDelete() {
    if (confirm("Are you sure you want to delete this item?")) {
        return true;
    } else {
        return false;
    }
}

</script>
<style>
.filter-form label {
  float: left;
  margin-right: 10px;
}
.filter-form p {
  float: left;
  margin-right: 10px;
}

.filter-form input[type="text"] {
  width: 200px;
  float: left;
  border: 1px solid #ccc;
  height: 40px;


}

.filter-form button[type="submit"] {
  float: left;


}
</style>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-sm">
                        <div class="search-box me-2 d-inline-block">
                            <div class="position-relative">
                             

                                <form method="get">
                                    <div class="filter-form">
                                    {{ filter.form.as_p }}
                                    <button class="btn btn-success" type="submit">Filter</button>
                                    </div>
                                </form>


                            </div>
                        </div>
                    </div>
                    <!-- end col -->
                    <div class="col-sm-auto">
                        <div class="text-sm-end">
                            <a href="{% url 'customers:customer_create' %}" class="btn btn-success btn-rounded" id="addTransaction-btn"><i class="mdi mdi-plus me-1"></i> Add New Customer</a>
                        </div>
                    </div>
                    <!-- end col -->
                </div>
                <!-- end row -->
                <div class="">
                    <div class="table-responsive">
                        
                        {% block content %}
						  
						  
						   <table class="table customer-list-table align-middle table-nowrap dt-responsive nowrap w-100 table-borderless" id="transactionList-table">
						    <thead>
						      <tr>
						        <th>Customer ID</th>
						        <th>Bill Company</th>
						        <th>Bill First Name</th>
						        <th>Bill Last Name</th>
						        <th>Recurring Schedule</th>
						        <th>Bill Phone Number</th>
						        <th>Email</th>
                                <th>Action</th>

						      </tr>
						    </thead>
						    <tbody>
						      {% for customer in filter.qs %}
						        <tr>
						          <td>{{ customer.customer_id }}</td>
						          <td>{{ customer.bill_company }}</td>
						          <td>{{ customer.bill_first_name }}</td>
						          <td>{{ customer.bill_last_name }}</td>
						          <td>{{ customer.recurring_schedule }}</td>
						          <td>{{ customer.bill_phone_number }}</td>
						          <td>{{ customer.email }}</td>
                                  <td>
                                        <a href="{% url 'customers:customer_update' customer.pk %}" class="btn btn-outline-primary btn-sm">Update Record<i class="mdi mdi-pencil"></i></a>
                                        <a href="{% url 'customers:customer_delete' customer.pk %}"   class="btn btn-danger" >Delete</a>
                                    </td>

						        </tr>
						      {% empty %}
						        <tr>
						          <td colspan="7">No customers found.</td>
						        </tr>
						      {% endfor %}
						    </tbody>
						  </table>
						{% endblock %}

                    </div>
                </div>
            </div>
        </div>
        <!-- end card -->
    </div>
</div>
<!-- end row -->

{% endblock %}

{% block extra_content %}          
<!-- Modal -->
<div class="modal fade" id="removeItemModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm">
        <div class="modal-content">
            <div class="modal-body px-4 py-5 text-center">
                <button type="button" class="btn-close position-absolute end-0 top-0 m-3" data-bs-dismiss="modal" aria-label="Close"></button>
                <div class="avatar-sm mb-4 mx-auto">
                    <div class="avatar-title bg-primary text-primary bg-opacity-10 font-size-20 rounded-3">
                        <i class="mdi mdi-trash-can-outline"></i>
                    </div>
                </div>
                <p class="text-muted font-size-16 mb-4">Are you sure you want to remove this order?</p>
                
                <div class="hstack gap-2 justify-content-center mb-0">
                    <button type="button" class="btn btn-danger" id="remove-item">Remove Now</button>
                    <button type="button" class="btn btn-secondary" id="close-removeProjectModal" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
<!-- end removeItemModal -->